tool:
  name: pace-notes
  description: An AI tool that generates pace notes for CAF Members

Frontend:
  chat_interface:
    UI_layout:
      - navigation_bar: top
      - chat_history: none
      - user_input: text_input
      - submit_button: send
      - response_output: text_output
      # TODO: Implement rank selection
      # - dropdown_menu: rank selection
      #   dynamic_options:
      #     - path: /src/prompts/competencies{rank}.md

knowledge_base:
  sources:
    # TODO: Implement rank-based competencies
    # - type: files
    #   path: /src/prompts/competencies{rank}.md
    #   format: markdown table
    #   usage:
    #     - dynamically added into LLM system prompt
    - type: files
      path: /src/policies/pace-note/competency-{{rank}}.md  # for now /policies/pace-note/competency.md
      format: markdown
      usage:
        - dynamically added into LLM system prompt
    - type: files
      path: /src/policies/pace-note/example_notes.md
      format: markdown
      usage:
        - dynamically added into LLM system prompt
    - type: files
      path: /src/prompts/pace-note.md
      format: markdown
      usage:
        - main system prompt for the tool
endpoints:
  generate:
    path: /llm/pace-notes/generate
    methods: [POST]
    description: Generate pace notes using LLM
    parameters:
      temperature: 0.1

  main_LLM_API_provider:
    model: PACE_NOTE_MODEL
    temperature: 0.1
  backup_LLM_API_provider:
    model: BACKUP_PACE_NOTE_MODEL
    num_ctx: BACKUP_PACE_NOTE_NUM_CTX
    batch_size: BACKUP_PACE_NOTE_BATCH_SIZE
    temperature: 0.1


state_management:
  type: in_memory
  chat_history: ephemeral

security:
  rate_limiting:
    strategy: sliding_window
    identification:
      primary: ip_address
      secondary:
        - session_token:
            type: jwt
            expiry: 24 hours
            purpose: session_token
    limits:
      - 15 requests per hour
      - 50 requests per day

monitoring and logging:
  basic_metrics: # open telemetry compatible metrics
    - No logging of user data
    - No logging of user messages # unless in debug mode
    - All logs are in memory only
    - server_health
    - Request and general usage
    - Active users per 15 minute intervals
    - error_logs